### ISSUE TITLE
how to add a folder to whitelist?

### ISSUE THREAD

**Issue by sdokio** [easingthemes/ssh-deploy#12]
I need deploy directory `/data/www/`, but I don't want to overwrite `/data/www/a/b/`, is there any way to implement this?

**Comment by KosratDAhmad** [comment]
I have the same situation I want to keep `images` folder between deploys

**Comment by richchurcher** [comment]
Setting `ARGS`, you can add an rsync `--exclude` flag. So, for example:
```
      - name: deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          ARGS: "-rltgoDzvO --delete --exclude=images"
```
