### ISSUE TITLE
Rsync error status code 255

### ISSUE THREAD

**Issue by shimingw** [easingthemes/ssh-deploy#14]
actions  config
```yml
  with:
    TARGET: /home/REMOTE_USER/
  env:
    SSH_PRIVATE_KEY: ***
    ARGS: -avz --delete
    REMOTE_USER: ***
    REMOTE_HOST: ***
    SOURCE: .vuepress/dist
    TARGET: /usr/share/nginx/html
```
actions error log
```
GITHUB_WORKSPACE /home/runner/work/vpblog/vpblog
Creating /home/runner/.ssh dir in  /home/runner/work/vpblog/vpblog
Creating /home/runner/.ssh/known_hosts file in  /home/runner/work/vpblog/vpblog
✅ Ssh key added to `.ssh` dir  /home/runner/.ssh/deploy_key
Starting Rsync Action: /home/runner/work/vpblog/vpblog/.vuepress/dist to ***@***:/usr/share/nginx/html
⚠️ Rsync error rsync exited with code 255
 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.267.1/externals/node12/bin/node]
 2: 0xa4e219  [/home/runner/runners/2.267.1/externals/node12/bin/node]
 3: 0xba5d59  [/home/runner/runners/2.267.1/externals/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.267.1/externals/node12/bin/node]
 5: 0x13750d9  [/home/runner/runners/2.267.1/externals/node12/bin/node]
```
