### ISSUE TITLE
Pnpm: command not found

### ISSUE THREAD

**Issue by Ardear** [easingthemes/ssh-deploy#157]
I'm trying to deploy a front-end project to a remote server using Github Action, and I confirme that the remote server has downloaded pnpm.

Github Action:
```
    - name: Deploy public
      uses: easingthemes/ssh-deploy@v4.1.8
      env:
          IP: ${{ secrets.IP }}
          SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }}
          SOURCE: "pnpm-lock.yaml" 
          REMOTE_HOST: ${{ env.SERVER_HOST }}
          REMOTE_USER: ${{ env.USER_NAME }}
          TARGET: '/home/ubuntu/test/' 
      with: 
          SCRIPT_AFTER: |
            cd /home/ubuntu/test
            pnpm start
            docker start nginx
```

Log:
```
Executing remote script: ssh -i /home/runner/.ssh/deploy_key_***_1691335359810 ***@***
✅ [CMD] Remote script executed. 
 nginx
 bash: line 2: pnpm: command not found

✅ [DONE] 
```

**Comment by Palaxx** [comment]
Hello @Laxy317 , 
I've the same issue of you but with `npm` and `pm2`, could you please share how you fixed it?

My SCRIPT_AFTER is the following: 
```yml
SCRIPT_AFTER: |
            pwd
            npm ci
            pm2 restart server
```

and I received 
```shell
bash: line 2: npm: command not found
bash: line 3: pm2: command not found
```

Thanks

**Comment by Palaxx** [comment]
The problem is caused by the library execute the after script using `bash -c` which by default does not load the user configurations. 

I solve thanks to this [issue](https://github.com/appleboy/ssh-action/issues/44) in ssh-action repository executing the following commands: 
```shell
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2"
```

**Comment by alexandrtovmach** [comment]
Absolute path works well:

*to be 100%, better to force `change directory` command before run

```yaml
- name: Run deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}/web/yourproject
          EXCLUDE: ".git, .github, node_modules, .next"
          SCRIPT_AFTER: |
            cd ${{ secrets.DEPLOY_PATH }}/web/yourproject
            PNPM_PATH=${{ secrets.DEPLOY_PATH }}/.local/share/pnpm/pnpm
            echo "PNPM_PATH: $PNPM_PATH"
            $PNPM_PATH install
            $PNPM_PATH run build
            echo "Deployed successfully"
```
