### ISSUE TITLE
Deploy on sub-directories not working, only on root directory

### ISSUE THREAD

**Issue by devwdougherty** [easingthemes/ssh-deploy#162]
I have the following github workflow for my project:

```yaml
name: ObservatorioPolitico.info CI
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
  
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Hostinger Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./public ./resources ./routes ./app ./database ./config ./votorantim/routes"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
```

All the files are deployed successfully in the first 6 directories, but the routes subdirectory inside ./votorantim it's not. Any ideas?
