### ISSUE TITLE
SCRIPT_AFTER not respecting REMOTE_PORT

### ISSUE THREAD

**Issue by OndraM** [easingthemes/ssh-deploy#163]
Hi, 
when I try to use SCRIPT_AFTER, it times out on connection refused, and it seems it is using port 22, even though I use REMOTE_PORT to set different port (and the rsync deployment is working properly on this port).

```yaml
      - name: Deploy
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlDzvc -i --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ vars.REMOTE_TARGET  }}
          SCRIPT_AFTER: |
            pwd
```

```
" bash -s' < local_ssh_script-after.sh
ssh: connect to host *** port 22: Connection timed out
```

From quick look into the source, it seems in [remoteCmd](https://github.com/easingthemes/ssh-deploy/blob/main/src/remoteCmd.js#L2C37-L2C47) the `remotePort` is imported from [inputs.js](https://github.com/easingthemes/ssh-deploy/blob/main/src/inputs.js), however, there is no such variable.
