### ISSUE TITLE
How to skip rsync ?

### ISSUE THREAD

**Issue by abcfy2** [easingthemes/ssh-deploy#165]
I just want to execute ssh command on remote ssh server. So I omitted `SOURCE` and `TARGET`. But seems rsync still executed.

**Comment by codespearhead** [comment]
@abcfy2 Show us your yml file.

**Comment by abcfy2** [comment]
```yml
  deploy:
    runs-on: ubuntu-latest
    needs:
      - docker-build
    if: ${{ contains(
      fromJson('["push", "workflow_dispatch"]'),
      github.event_name) &&
      contains(
      fromJson('["main"]'),
      github.ref_name)
      }}
    steps:
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SCRIPT_AFTER: |
            echo hello
```
