### ISSUE TITLE
how to send hidden files?

### ISSUE THREAD

**Issue by felipemjesus** [easingthemes/ssh-deploy#168]
I tried using the **ARGS** parameter with the `--include=.*` argument, but it didn't work.

Examples of hidden files: **.env, .htaccess**.

Here's how I set it up:
```
      - name: Sending files for server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvOavh --include=.*"
          SOURCE: "./dist/*"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET_PRODUCTION }}
```

**Comment by codespearhead** [comment]
@felipemjesus Try running it [without the asterisk](https://github.com/easingthemes/ssh-deploy#issues): `--include=.`

**Comment by felipemjesus** [comment]
Reading the article mentioned, I understood that there was no problem with using `--include`, the problem was with the asterisk I entered in the **SOURCE** parameter.

Here is the workflow with the correction:

```
      - name: Sending files for server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvOavh"
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET_PRODUCTION }}
```

And thank you very much for your help.
