### ISSUE TITLE
Rsync Action fails with Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by cryocaustik** [easingthemes/ssh-deploy#17]
I am running into an error on the `Rsync Action` and cannot figure out what is causing it.
I followed your instructions on creating a key, ensured the directory paths were correct, but each time I get the same error.

My workflow:
```yml
name: SSH Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn

      - name: Build site
        run: yarn build

      - name: Deploy to Production server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RANDOM_CALC_DEPLOY_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
```

the build output:
![image](https://user-images.githubusercontent.com/15346996/92870131-660ecf00-f3b8-11ea-833e-1f5d769cc4bc.png)
