### ISSUE TITLE
Wired permission denied,when connect to host could help me analysis where i am wrong

### ISSUE THREAD

**Issue by joebnb** [easingthemes/ssh-deploy#170]
in use ssh-deploy as readme recommend and write a test deploy script,i was tryed all ways that i can considered.but it did not work, if have spare time.

this is clue of my test.
![image](https://github.com/easingthemes/ssh-deploy/assets/1646883/a9cd7996-f200-4f9b-aa32-ebbfc5b754ec)

in this image is:
   * the runner can reach target machine
   * whoami is `runner`
   * ls .ssh dir it's shows runner **have rights of know_hosts and private key file,but use cat (ls /pathTo/.ssh) it shows permission denied,it's wired**

i doubt the private key did work well,so i copy key in to a ubuntu container(runner also running under a contaienr),then trying same command to connect target host.
![image](https://github.com/easingthemes/ssh-deploy/assets/1646883/053c75eb-b2cd-406f-8249-cde130b992f3)

![image](https://github.com/easingthemes/ssh-deploy/assets/1646883/c7101684-f155-459c-bce7-b77bd90f2a9a)

the key configuration is works for test container and this is the permission of test file and ownership，in this working case  cat ls was readout the file content

![image](https://github.com/easingthemes/ssh-deploy/assets/1646883/613afd46-9f5f-41f5-9817-eebb208129bf)

the deploy script is 
```yaml
          - name: Echo user
            run: echo ${{ vars.REMOTE_USER }} && ping -c 2 -W 3 ${{ vars.REMOTE_HOST }}
          - name: Deploy
            uses: easingthemes/ssh-deploy@main
            with:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              ARGS: "-rlgoDzvc -i --delete"
              REMOTE_HOST: ${{ vars.REMOTE_HOST }}
              REMOTE_USER: ${{ vars.REMOTE_USER }}
              TARGET: ${{ vars.REMOTE_TARGET }}
              SOURCE: "src/"
              EXCLUDE: "/dist/, /node_modules/"
              SCRIPT_BEFORE: |
                  whoami
                  ls -al
              # SCRIPT_AFTER: |
              #     whoami
              #     ls -al
              #     echo "done!"
          - name: look perm
            run: whoami && ls -la /home/runner/.ssh  && cat $(ls /home/runner/.ssh)
```

where i am wrong.
