### ISSUE TITLE
deploy to server is slowly

### ISSUE THREAD

**Issue by yinguangyao** [easingthemes/ssh-deploy#18]
when I use this action, deploy to server always spend many time.
![image](https://user-images.githubusercontent.com/16210045/93022740-580db800-f61d-11ea-909a-0f879e851bd7.png)

And my yml is as follows:
```
name: deploy
on:
  push:
    branches:
      - master
    paths-ignore:   # 变更不触发部署
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:   # 变更不触发部署
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            SOURCE: "build/"
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_USER: ${{ secrets.SSH_USERNAME }}
            TARGET: ${{ secrets.REMOTE_TARGET }}

```

**Comment by bespoyasov** [comment]
@yinguangyao, I had the same problem. 

Then, I found [this post](https://logansnotes.com/posts/automatic-site-deploy-via-github-action/), which helped me with the flags setup. 

It recommends to use `-rlgoDzvc` instead of `-rltgoDzvO` since the modification time of freshly checked out files is always different from those on server. So `rsync` sends _all the files_ to the server.

I switched to those flags as well and it [drastically decreased the deploy time from _4 minutes to 14 seconds_](https://github.com/bespoyasov/www/runs/1298658124?check_suite_focus=true):
<img width="1078" alt="«Screenshot» 2020-10-23 at 18 04 02" src="https://user-images.githubusercontent.com/9102374/97020388-2b24bd00-155a-11eb-9fb2-496e9774924b.png">

Hope this helps!

**Comment by Triloworld** [comment]
Yep. I agree that "c" is for checksum and will be better to update that in doc for convenient and fix some future new issues there.
I'am for adding to ARGS section, link to man page of [rsync](https://man7.org/linux/man-pages/man1/rsync.1.html)

**Comment by xwzbupt** [comment]
```
      - name: Deploy to Aliyun Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: ${{ secrets.SOURCE }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: ${{ secrets.TARGET }}
```
I also met this probleam and solved it.
