### ISSUE TITLE
Rsync ARGS not working

### ISSUE THREAD

**Issue by NicolasJourdan** [easingthemes/ssh-deploy#189]
Hello,

I'm using the `ARGS` environment variable to add some arguments to `rsync` however it seems like the arguments are not add to the `rsync` command. 

My cd configuration : 

```yml
            - name: Ssh deploy
              uses: easingthemes/ssh-deploy@v5.0.3
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
                  ARGS: "-rlgoDzvci"
                  REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
                  REMOTE_USER: ${{ secrets.DEPLOY_USER }}
                  TARGET: ${{ secrets.DEPLOY_TARGET }}
                  SCRIPT_BEFORE: |
                    whoami
                    ls -al
                  SCRIPT_BEFORE_REQUIRED: true
                  SCRIPT_AFTER: |
                    whoami
                    ls -al
                    echo $RSYNC_STDOUT
                  SCRIPT_AFTER_REQUIRED: true
```
The github action fails : 

```
rsync: chgrp "***/.git/" failed: Operation not permitted (1)
...
rsync: chgrp "***/project/composer.json" failed: Operation not permitted (1)
...
```

I tried to sync the file from my PC using the same ssh key and it worked. 

```bash
rsync project/composer.json ****@****:/home/****/www/project/composer.json -rlgoDzvci
```
