### ISSUE TITLE
Failed execution of SCRIPT_AFTER should result in failure of the workflow step

### ISSUE THREAD

**Issue by cyril23** [easingthemes/ssh-deploy#195]
So this is my workflow yaml:
```
name: Manual deploy my-remote-host.tld

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: NPM install frontend
        run: |
          cd frontend/
          npm install
          npm run build --if-present

      - name: GO back to root
        run: cd ..

      - name: List output files
        run: ls

      - name: Deploy to Server my-remote-host.tld
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GLOBAL_RUNNER_SSH_PRIVATE_KEY }}
          ARGS: '-a4 --delete --no-o --no-g'
          SOURCE: '/frontend /backend package.json .env.production'
          REMOTE_HOST: my-remote-host.tld
          REMOTE_USER: ${{ secrets.GLOBAL_USER }}
          TARGET: /node/myservice/
          EXCLUDE: '/frontend/node_modules, /frontend/public, /frontend/src, /frontend/package-lock.json, /frontend/package.json, /frontend/README.md'
          SSH_CMD_ARGS: '-o StrictHostKeyChecking=no, -o AddressFamily=inet'
          SCRIPT_AFTER: |
            cd /node/myservice
            mv .env.production .env
            npm install
            /bin/systemctl restart myservice.service
```

So yesterday I got this result:
<img width="1646" alt="image" src="https://github.com/user-attachments/assets/5f0da677-428b-452d-848e-16d3a2bd091b">

So the workflow step `Deploy to Server my-remote-host.tld` apparently succeeded although the SCRIPT_AFTER execution failed

```
⚠️ [CMD] Remote script failed: Command failed: DEBIAN_FRONTEND=noninteractive ssh -p 22 -i /home/myservice/.ssh/deploy_key_***_1733310164670 -o StrictHostKeyChecking=no ***@my-remote-host.tld 'RSYNC_STDOUT="" bash -s' < local_ssh_script-after-da7b2372-c728-4a72-bf4c-f0f4c76301c0.sh
Permission denied, please try again.
Permission denied, please try again.
***@my-remote-host.tld: Permission denied (publickey,password).
 
  Permission denied, please try again.
Permission denied, please try again.
***@my-remote-host.tld: Permission denied (publickey,password).

⚠️ [CMD] Remote script failed: Command failed: DEBIAN_FRONTEND=noninteractive ssh -p 22 -i /home/myservice/.ssh/deploy_key_***_1733310164670 -o StrictHostKeyChecking=no ***@my-remote-host.tld 'RSYNC_STDOUT="" bash -s' < local_ssh_script-after-da7b2372-c728-4a72-bf4c-f0f4c76301c0.sh
Permission denied, please try again.
Permission denied, please try again.
***@my-remote-host.tld: Permission denied (publickey,password).
```

Can you make the whole workflow step (in my case `Deploy to Server my-remote-host.tld`) fail please, in case of problems with the SCRIPT_AFTER execution? 

Github always notifies me if any step fails, so I would like to get a notification in case of SCRIPT_AFTER execution failure, too.
