### ISSUE TITLE
Rsync exited with code 255

### ISSUE THREAD

**Issue by ChidaoDouyu** [easingthemes/ssh-deploy#199]
### ERROR
``` 
Run easingthemes/ssh-deploy@v2.0.7
  
GITHUB_WORKSPACE /home/runner/work/ChidaoDouyu.github.io/ChidaoDouyu.github.io
Creating /home/runner/.ssh dir in  /home/runner/work/ChidaoDouyu.github.io/ChidaoDouyu.github.io
Creating /home/runner/.ssh/known_hosts file in  /home/runner/work/ChidaoDouyu.github.io/ChidaoDouyu.github.io
✅ Ssh key added to `.ssh` dir  /home/runner/.ssh/deploy_key
Starting Rsync Action: /home/runner/work/ChidaoDouyu.github.io/ChidaoDouyu.github.io/docs/.vuepress/dist to ***@***:/web/blog
⚠️ Rsync error rsync exited with code 255
----- Native stack trace -----
 1: 0xd4c8f0  [/home/runner/runners/2.322.0/externals/node20/bin/node]
 2: 0xf6e88f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/home/runner/runners/2.322.0/externals/node20/bin/node]
 3: 0xf6f0fd  [/home/runner/runners/2.322.0/externals/node20/bin/node]
 4: 0xf6f5c5 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.322.0/externals/node20/bin/node]
 5: 0x[19](https://github.com/ChidaoDouyu/ChidaoDouyu.github.io/actions/runs/13346248095/job/37277404101#step:7:20)79df6  [/home/runner/runners/2.322.0/externals/node[20](https://github.com/ChidaoDouyu/ChidaoDouyu.github.io/actions/runs/13346248095/job/37277404101#step:7:21)/bin/node]
----- JavaScript stack trace -----
1: /home/runner/work/_actions/easingthemes/ssh-deploy/v2.0.7/dist/index.js:495:29
2: /home/runner/work/_actions/easingthemes/ssh-deploy/v2.0.7/dist/index.js:411:7
3: emit (node:events:519:28)
4: ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

### WORKFLOW
```
- name: 推送到云服 //Push to VPs
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete --exclude='*.pyc'"
          SOURCE: "docs/.vuepress/dist"
          REMOTE_HOST: ${{ secrets.IP }}
          REMOTE_USER: ${{ secrets.user }}
          TARGET: /web/blog
```

### config
RSAAuthentication yes
PubkeyAuthentication yes
PermitRootLogin yes

user: root
IP have been set.
access_token: private_key
authorized_keys: pub_key
