### ISSUE TITLE
Allow running of additional commands on remote server

### ISSUE THREAD

**Issue by srinathreddydudi** [easingthemes/ssh-deploy#25]
It would be great to allow running of additional commands on remote server after the files are deployed. 
Example restarting web server.

**Comment by JaimeObregon** [comment]
+1. Another example: emptying the production folder before the deploy.

**Comment by daiwa233** [comment]
> It would be great to allow running of additional commands on remote server after the files are deployed.
> Example restarting web server.
I have the same needs

**Comment by sergejkaravajnij** [comment]
You can use regular `ssh` to execute commands on the remote server.
A couple of simple examples I use in my deployment scripts
```yml
      - name: Performing before deployment tasks
        run: "ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}} 'mkdir -p --mode=0775 ${{ env.remote-full-path }}'"

      - name: Permorming after deployment scripts
        run: "ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}} 'bash ${{ env.remote-full-path }}/after_deploy.bash'"
```
