### ISSUE TITLE
Additional ARGS not work

### ISSUE THREAD

**Issue by SergeShkurko** [easingthemes/ssh-deploy#26]
When i run locally `rsync -avzr --delete --exclude={'docker/data','docker/logs','.env','config.yaml','vendor','.git'} ./ ...`
rsync normally push changes at remote server
![image](https://user-images.githubusercontent.com/18213789/105511919-85602600-5ce1-11eb-8ce7-a380f98c6ebe.png)

When run from github action same command (config attached) i see only deletions
![image](https://user-images.githubusercontent.com/18213789/105512093-bfc9c300-5ce1-11eb-9255-636ce9732de2.png)
as if all arguments don't work except --delete

if I remove the attribute --delete, the changes do not come to the server

```yaml
name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SOURCE: "./"
          ARGS: "-avzr --delete --exclude={'docker/data','docker/logs','.env','config.yaml','vendor','.git'}"
       
```
