### ISSUE TITLE
Rsync is just emptying folder, not copying anything

### ISSUE THREAD

**Issue by benjitusk** [easingthemes/ssh-deploy#30]
I might be doing this wrong (probably), but every time this workflow executes, the destination folder is just empty.
Here is my workflow:

```YAML
name: SSH Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: 22
          TARGET: ${{secrets.REMOTE_TARGET}}
          ARGS: "-rltgoDzvO" # optional, default is -rltgoDzvO
```
The logs look like this:

```
 1: Run easingthemes/ssh-deploy@v2.1.5
10: [general] GITHUB_WORKSPACE:  /home/runner/work/AllKnowingRedditBot/AllKnowingRedditBot
11: [SSH] Creating /home/runner/.ssh dir in  /home/runner/work/AllKnowingRedditBot/AllKnowingRedditBot
12: ✅ [SSH] dir created.
13: [SSH] Creating /home/runner/.ssh/known_hosts file in  /home/runner/work/AllKnowingRedditBot/AllKnowingRedditBot
14: ✅ [SSH] file created.
15: ✅ Ssh key added to `.ssh` dir  /home/runner/.ssh/deploy_key
16: [Rsync] Starting Rsync Action: /home/runner/work/AllKnowingRedditBot/AllKnowingRedditBot/ to ***@***:***
17: ✅ [Rsync] finished. sending incremental file list
```
I think the problem _could_ be that `GITHUB_WORKSPACE` is a double nested folder (AllKnowingRedditBot/AllKnowingRedditBot), but further than that, I'm really lost here.
