### ISSUE TITLE
 Error: The log was not found. It may have been deleted based on retention settings. 

### ISSUE THREAD

**Issue by sebastienserre** [easingthemes/ssh-deploy#46]
Hello,

Here's my yml file:
```
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: npm init
        run: npm init -y
      - name: Run build task
        run: npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"

```
At the end of the deployment, I've the error: ` Error: The log was not found. It may have been deleted based on retention settings. `
![screenshot-2021-05-08-14-39](https://user-images.githubusercontent.com/3902621/117539512-4beec480-b00b-11eb-9eaa-16471417c052.png)

Do you know why ?

**Comment by sleshJdev** [comment]
Same issue for me...

**Comment by sleshJdev** [comment]
That's the manifest which works for me:
```
name: CI
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy frontend
      uses: easingthemes/ssh-deploy@v2.1.5    
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-av"
        SOURCE: "./frontend/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
```

The only thing I did is specify another set of keys for rsync: `ARGS: "-av"`
