### ISSUE TITLE
Bad authentication type; allowed types: ['publickey']

### ISSUE THREAD

**Issue by yringler** [easingthemes/ssh-deploy#47]
I'm getting this error.
> Bad authentication type; allowed types: ['publickey']

With this config
```
      - name: scp pipelines
                uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
                   with:
                    host: ${{ secrets.DO_HOST }}
                  user: ${{ secrets.DO_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  scp: |
      './client/dist/green-client/*' => /home/github/admin/client/dist
```

Any suggestions?

```
Run cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
  with:
    host: ***
    user: ***
    key: ***
    scp: './client/dist/green-client/*' => /home/***/admin/client/dist
  
    port: 22
    connect_timeout: 30s
  env:
    working-directory: ./client
/usr/bin/docker run --name a33c1dc07c228dad94bfb95d982cd162088fa_7f679a --label 8a33c1 --workdir /***/workspace --rm -e working-directory -e INPUT_HOST -e INPUT_USER -e INPUT_KEY -e INPUT_SCP -e INPUT_PORT -e INPUT_PASS -e INPUT_CONNECT_TIMEOUT -e INPUT_FIRST_SSH -e INPUT_LAST_SSH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_***_home":"/***/home" -v "/home/runner/work/_temp/_***_workflow":"/***/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/***/file_commands" -v "/home/runner/work/admin/admin":"/***/workspace" 8a33c1:dc07c228dad94bfb95d982cd162088fa
+++++++++++++++++++STARTING PIPELINES+++++++++++++++++++
SSH-SCP-SSH no first_ssh input found
+++++++++++++++++++Pipeline: RUNNING SCP+++++++++++++++++++
Connect error
Bad authentication type; allowed types: ['publickey']
+++++++++++++++++++END PIPELINES+++++++++++++++++++
```
