### ISSUE TITLE
Feature Request - Connect to SSH Host through Jump-box

### ISSUE THREAD

**Issue by iuriandreazza** [easingthemes/ssh-deploy#63]
Hi,

It would be nice if we could setup a jump-box ssh tunnel to send the artefacts to the destiny host.

Something like this:
```yaml
- name: Deploy through Jump-box
         ...
          uses: easingthemes/ssh-deploy@main
          jumpbox: 
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST_DEVELOP }}
            REMOTE_USER: ${{ secrets.REMOTE_USER_DEVELOP }}
          ... 
```
