### ISSUE TITLE
Does not run command in ssh?

### ISSUE THREAD

**Issue by rodriguesfas** [easingthemes/ssh-deploy#76]
Does not run command in ssh?

Hello, excellent work this script to deploy, I have used it in PHP project and it has worked wonderfully.

I recently decided to use your deploy script for golang application, it runs perfectly without any error, sends the binary to the server in the specified path.

What happens is a snippet of code I added for it to run the binary in the background. It doesn't run, could you help me find out what I've been doing wrong?

Here's the script I'm using, thank you in advance for your attention. Hug.

```
name: 🚀 Deploy on push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.HOST_PORT }}
          SOURCE: "/go.realm.com.br"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
          run: |
            cd .. && 
            cd /home/username && 
            chmod +x /home/username/go.realm.com.br && 
            nohup ./go.realm.com.br &
```

**Comment by zulaica** [comment]
It looks to me like it may be an indentation issue. Perhaps this will work?

```
name: 🚀 Deploy on push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.HOST_PORT }}
          SOURCE: "/go.realm.com.br"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        run: |
          cd .. && 
          cd /home/username && 
          chmod +x /home/username/go.realm.com.br && 
          nohup ./go.realm.com.br &
```
